// Generated by CoffeeScript 1.10.0
$(document).ready(function() {
  var $flottante, $fond, $main, $navigation, $window, History, activate_navigation, deploy_two, desactivate_navigation, root, success, undeploy_two, writeText;
  $navigation = $('#navigation');
  $main = $('main');
  $fond = $('#fond');
  $window = $(window);
  $flottante = $('#nav-flottante');
  root = typeof exports !== "undefined" && exports !== null ? exports : this;
  root.navigation_top = $('#nav-activites').css('top');
  root.main_top = $main.css('top');
  root.principal = $('#principal');
  root.principal_top = root.principal.offset().top;
  root.deployed = false;
  $(window).resize(function() {
    $main.attr('style', "");
    $navigation.attr('style', "");
    root.navigation_top = $('#nav-activites').css('top');
    root.main_top = $main.css('top');
  });
  deploy_two = function() {
    var tl;
    tl = new TimelineMax({
      tweens: [
        TweenMax.to($navigation, 1, {
          top: (-parseInt(root.navigation_top)) + "px",
          ease: Power4.easeOut
        }), TweenMax.to($main, 1, {
          top: (parseInt(root.main_top) - parseInt(root.navigation_top) * 0.7) + "px",
          opacity: 0.15,
          ease: Power4.easeOut
        })
      ]
    });
  };
  undeploy_two = function() {
    var tl;
    tl = new TimelineMax({
      tweens: [
        TweenMax.to($navigation, 1, {
          top: "0px",
          ease: Power4.easeOut
        }), TweenMax.to($main, 1, {
          top: root.main_top,
          opacity: 1,
          ease: Power4.easeOut
        })
      ]
    });
  };
  activate_navigation = function() {
    $('#activites a').mouseenter(deploy_two);
    $navigation.mouseleave(undeploy_two);
    $('#flot-activites').mouseenter(function() {
      return $flottante.addClass('flot-deployed');
    });
    return $flottante.mouseleave(function() {
      return $flottante.removeClass('flot-deployed');
    });
  };
  desactivate_navigation = function() {
    $('#activites a').off('mouseenter');
    $navigation.off('mouseleave');
    $('#flot-activites').off('mouseenter');
    return $flottante.off('mouseleave');
  };
  activate_navigation();
  $('#flot-nav-titre').text($('h1.titre').text());
  $window.scroll(function() {
    TweenMax.set($fond, {
      backgroundPosition: "0px " + (-$window.scrollTop() * 0.2) + "px"
    });
    if (parseInt($window.scrollTop()) > parseInt(root.principal_top)) {
      $flottante.addClass('flot-appeared');
    } else {
      $flottante.removeClass('flot-deployed');
      $flottante.removeClass('flot-appeared');
    }
  });
  History = window.History;
  if (!History.enabled) {
    return false;
  }
  History.Adapter.bind(window, 'statechange', function() {
    var State, cible;
    State = History.getState();
    cible = State.data.target;
    return $.ajax({
      url: "html/" + cible,
      success: success
    });
  });
  $('#navigation').on('click', 'a', function(event) {
    var lien;
    event.preventDefault();
    desactivate_navigation();
    lien = $(this).attr('href');
    if (lien !== '#') {
      History.pushState({
        target: lien
      }, $(this).attr('data-titre'), lien);
    }
  });
  $flottante.on('click', 'a', function(event) {
    var lien;
    event.preventDefault();
    desactivate_navigation();
    lien = $(this).attr('href');
    if (lien !== '#') {
      History.pushState({
        target: lien
      }, $(this).attr('data-titre'), lien);
    }
  });
  success = function(data, status, xml) {
    var timeline;
    timeline = new TimelineMax();
    timeline.to($main, 0.4, {
      opacity: 0,
      onComplete: writeText,
      onCompleteParams: [data]
    });
    if ($flottante.hasClass('flot-appeared')) {
      $flottante.removeClass('flot-deployed').removeClass('flot-appeared').addClass('flot-triggered');
    }
  };
  return writeText = function(data) {
    var contenu, tm;
    tm = new TimelineMax();
    tm.set($main, {
      text: data
    });
    root.principal = $('#principal');
    root.principal_top = root.principal.offset().top;
    contenu = root.principal.html();
    $('#flot-nav-titre').text($('h1.titre').text());
    tm.set(root.principal, {
      opacity: 0
    });
    if ($flottante.hasClass('flot-triggered')) {
      tm.to(window, 0.4, {
        scrollTo: 0
      });
    }
    tm.call(undeploy_two);
    tm.from($('main h1.titre'), 0.6, {
      scale: 0.5,
      ease: Elastic.easeOut.config(0.6, 0.6)
    });
    tm.to(root.principal, 1, {
      opacity: 1
    });
    activate_navigation();
  };
});
